name: wekeo4oceans
channels:
  - conda-forge
  - cmts
  - eumetsat
  - coecms
dependencies:
  - conda-forge::python=3.8
  - conda-forge::notebook
  - conda-forge::xarray
  - conda-forge::netcdf4
  - conda-forge::shapely
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::ipywidgets
  - conda-forge::scikit-image
  - conda-forge::plotly
  - conda-forge::bokeh
  - conda-forge::ipykernel
  - conda-forge::cmocean
  - conda-forge::opencv
  - conda-forge::requests
  - conda-forge::beautifulsoup4
  - conda-forge::owslib
  - cmts::hda=1.1
  - cmts::eumartools
  - eumetsat::eumdac
  - coecms::xmhw=0.8.0

